services:
    invhome-web:
        build: .
        command: ["/usr/bin/supervisord"]
        container_name: invhome-py
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
        ports:
            - "8378:8000"
        networks:
            - invhome-net

networks:
    invhome-net:
        driver: bridge
