[unix_http_server]
file=/tmp/supervisord.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/usr/src/logs/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=/usr/src/logs

[supervisorctl]
serverurl=unix:///tmp/supervisord.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:runserver]
command=uvicorn main:app --host 0.0.0.0 --port 8000 --reload --proxy-headers
autostart=true
autorestart=true
stdout_logfile=/usr/src/logs/runserver.log
stderr_logfile=/usr/src/logs/runserver_error.log

[program:cron]
command=cron -f
autostart=true
autorestart=true
stdout_logfile=/usr/src/logs/cron.log
stderr_logfile=/usr/src/logs/cron_error.log
