[unix_http_server]
file=/tmp/supervisord.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/usr/src/logs/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=/usr/src/logs

[supervisorctl]
serverurl=unix:///tmp/supervisord.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:react]
command=pnpm run dev --host
autostart=true
autorestart=true
stdout_logfile=/usr/src/logs/react.log
stderr_logfile=/usr/src/logs/react_error.log
